---
title: "7q11.23 translation project - isogenic Neurons proteomics"
output:
    html_document:
        toc: true
        toc_float: true
        theme: 'cerulean'
        highlight: 'tango'
        code_folding: hide
        df_print: paged
---

=====================
Pierre-Luc Germain - `r format(Sys.time(), '%d %B, %Y')`
<br><br><br>

# Preprocessing

```{r}
suppressPackageStartupMessages({
  library(GTscripts)
  library(SummarizedExperiment)
  library(DEP)
  library(DT)
})
printTable <- function(x){
  datatable(x, filter="top", extensions = 'Buttons', 
            options = list(
              dom = 'Bfrtip',
              buttons = c('csv', 'excel')
            ))
}
source("../../misc.R")
source("../../misc/volcanoDEGs.R")
```

```{r, eval=FALSE}
e <- read.delim("isogenics_proteomics.input.txt.gz", header=T, stringsAsFactors = F)
e <- e[which(e$Reverse!="+" & e$Potential.contaminant != "+" & e$Only.identified.by.site !="+"), ]
ei <- e[,grep("LFQ.intensity",colnames(e),fixed=T)]
w <- which(!apply(ei,1,FUN=function(x){ any(is.na(x)) }))
ei <- ei[w,]
# aggregate technical replicates
smp <- sapply(colnames(ei),FUN=function(x){ strsplit(strsplit(x,".",fixed=T)[[1]][[3]], "_", fixed=T)[[1]][[1]] })
ag <- aggregate(t(ei),by=list(sample=smp), FUN=function(x){ x <- x[which(!is.na(x) & x>0)]; if(length(x)==0) return(0); mean(x) })
row.names(ag) <- ag[,1]; ag[,1] <- NULL
ag <- t(ag)
nbNA <- apply(ag,1,FUN=function(x){ sum(x==0)})
colnames(ag) <- paste0("LFQ.intensity.",rep(c("DUP","WBS","CTRL"),each=3),"_",rep(1:3,3))
d <- data.frame( label=paste0(rep(c("DUP","WBS","CTRL"),each=3),"_",rep(1:3,3)), 
                 condition=rep(c("DUP","WBS","CTRL"),each=3), 
                 replicate=rep(1:3,3), CN=rep(c(3,1,2),each=3),
                 stringsAsFactors = F)
e <- cbind(e[w,grep("LFQ.intensity",colnames(e),invert=T,fixed=T)],ag)
# we remove proteins with more than 4 missing values
e <- e[which(nbNA<=4),]

library(biomaRt)
ensembl = useMart("ensembl", dataset="hsapiens_gene_ensembl")
e$Protein.IDs <- gsub(";","/",e2$Protein.IDs,fixed=T)
pids <- unique(unlist(strsplit(as.character(e$Protein.IDs),"/")))
bm <- getBM(attributes=c("uniprotswissprot","hgnc_symbol","ensembl_gene_id"), filters="uniprotswissprot", values=pids, mart=ensembl)
bm2 <- plag(bm,by=bm$uniprotswissprot,agFun=function(x){ x <- x[x!=""]; paste(sort(unique(x)),collapse="; ")})

e2 <- e
e2$Gene.names <- sapply(strsplit(e2$Protein.IDs,"/",fixed=T), FUN=function(x){
  xo <- x
  x <- bm2[x,"hgnc_symbol"]
  x <- x[!is.na(x) & x!=""]
  if(length(x)==0){
    x <- xo
    x <- bm2[x,"ensembl_gene_id"]
    x <- x[!is.na(x) & x!=""]
    if(length(x)==0) x <- xo
  }
  paste(sort(unique(x)),collapse=",")
})
e2$Gene.ids <- sapply(strsplit(e2$Protein.IDs,"/",fixed=T), FUN=function(x){
  x <- bm2[x,"ensembl_gene_id"]
  x <- x[x!=""]
  paste(sort(unique(x)),collapse=",")
})
e2$nbProteins <- sapply(strsplit(e2$Protein.IDs,"/",fixed=T), FUN=function(x){
  return(length(x))
})
e2$Protein <- e2$Protein.IDs
un <- paste0(e2$Protein,".",e2$Gene.names)
w <- which(e2$nbProteins>2)
un[w] <- paste0("*",e2$nbProteins[w],".",e2$Gene.names[w])
w <- which(un %in% un[duplicated(un)])
un[w] <- paste0("*",e2$nbProteins[w],letters,".",e2$Gene.names[w])
row.names(e2) <- un

e2$name <- row.names(e2)
e2$ID <- e2$Protein
e2$nbPeptides <- e2$Peptide.counts..unique.
co <- grep("^LFQ\\.", colnames(e2), value=T)
se <- make_se(e2[,c(co,"name","ID","Protein","Gene.names","Gene.ids","nbProteins","nbPeptides")], 1:length(co), d)
intensities <- e2[,co]
colnames(intensities) <- colnames(se)
assays(se)[["intensity"]] <- intensities
assayNames(se)[1] <- "lognorm"
se <- se[,order(d$CN,row.names(d))]

plot_frequency(se)
plot_numbers(se)
se <- normalize_vsn(se)
sen <- impute(se, fun = "MinProb")
assays(se)[["imputed"]] <- assay(sen,"lognorm")
metadata(se)$method <- "Median top 3 peptides, VSN normalization, minProb imputation."
saveRDS(se, "../../clean/Neurons/Protein/Neurons.Protein.isogenic.SE.rds")
```

```{r, include=FALSE}
se <- readRDS("../../clean/Neurons/Protein/Neurons.Protein.isogenic.SE.rds")
sen <- se
assays(sen) <- assays(sen)[c(3,1,2)]
```


# WBS genes

```{r}
en <- get_df_wide(sen)
en <- en[which(en$Gene.names %in% WBSg1),]
row.names(en) <- en$Gene.names
en <- en[,colnames(se)]
byheatmap(en,scale="row",cluster_col=F)
```

# Comparison to controls

```{r}
sen <- test_diff(sen, type="manual", test=c("WBS_vs_CTRL","DUP_vs_CTRL","DUP_vs_WBS"))
sen <- add_rejections(sen, alpha = 0.05, lfc = log2(1.25))
res <- get_results(sen)

df <- get_df_wide(sen)
d <- sen@colData
row.names(df) <- df$name
df <- df[,-1]
library(limma)
reg <- topTable(eBayes(lmFit(df[,colnames(sen)], model.matrix(~CN,data=colData(sen)))),number=10000)

m <- DEP2dea(reg, res)

library(plotrix)
volcanoDEGs(subset_mDEA(m,"WBS"), main="WBS vs CTRL")
volcanoDEGs(subset_mDEA(m,"DUP"), main="DUP vs CTRL")
```

# Regression on copy-number
```{r}
volcanoDEGs(m, main="Regression on copy-number", alpha = 0.05)
saveRDS(m, file="../../clean/Neurons/Protein/Neurons.Protein.isogenic.DEA.rds")
```

# Enrichments

When there are multiple proteins for a gene, we keep the most significant one.

## WBS vs CTRL
```{r}
EA <- list()
cr <- cameraWrapper(toSymbol(subset_mDEA(m,"WBS")))
EA[["WBS"]] <- list(camera=cr)
printTable(cr)
```

## DUP vs CTRL
```{r}
cr <- cameraWrapper(toSymbol(subset_mDEA(m,"DUP")))
EA[["DUP"]] <- list(camera=cr)
printTable(cr)
```

## DUP vs CTRL
```{r}
cr <- cameraWrapper(toSymbol(subset_mDEA(m,"DUPvsWBS")))
EA[["DUPvsWBS"]] <- list(camera=cr)
printTable(cr)
```

## Regression
```{r}
cr <- cameraWrapper(toSymbol(m))
EA[["reg"]] <- list(camera=cr)
printTable(cr)

saveRDS(EA, file="../../clean/Neurons/Protein/Neurons.Protein.isogenic.DEA.enrichments.rds")
```

