---
title: "Neurons 1"
output:
    html_document:
        toc: true
        toc_float: true
        theme: 'cerulean'
        highlight: 'tango'
        code_folding: hide
        df_print: paged
---

<style>
  .main-container {
    max-width: 1500px !important;
  }
</style>

=====================
Pierre-Luc Germain - `r format(Sys.time(), '%d %B, %Y')`
<br><br><br>

```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(ComplexHeatmap)
  library(SEtools)
  library(sechm)
  library(ggplot2)
  library(cowplot)
  library(ggrepel)
  library(grid)
})
source("../misc.R")
source("../colors.R")
source("../misc/compare_and_overlay_TE.R")
source("../misc/GO.R")
source("../misc/enrichmentAnalysis.R")
load("../extData/complexes.RData")
```

```{r}
gsets <- getMsigSets()
names(gsets) <- gsub("GOMF|GOBP|GOCC","GO",names(gsets)) # for newer versions
```

# Neurons

```{r}
deas <- list( RNA=readRDS("../clean/Neurons/RNA/Neurons.RNA.isogenic.DEA.rds"),
              TE=readRDS("../clean/Neurons/TE/Neurons.TE.isogenic.DEA.rds"),
              Protein=readRDS("../clean/Neurons/Protein/Neurons.Protein.isogenic.DEA.rds") )
deas <- lapply(deas, toSymbol)
rna.dea.pD <- toSymbol(readRDS("../clean/Neurons/RNA/Neurons.RNA.patientDerived.DEA.rds"))
```


# Merged analysis of the two systems

```{r, warning=FALSE, message=FALSE}
dea.rna <- toSymbol(readRDS("../clean/Neurons/RNA/Neurons.RNA.merged.DEA.rds"))
se.rna <- toSymbol(readRDS("../clean/Neurons/RNA/Neurons.RNA.merged.SE.rds"))
se.rna <- se.rna[,se.rna$genotype!="AtWBS"]
se.rna$genotype <- droplevels(se.rna$genotype)
levels(se.rna$genotype) <- c("CTL","WBS","7Dup")
ea.rna <- readRDS("../clean/Neurons/RNA/Neurons.RNA.merged.DEA.enrichments.rds")
se.rna$Dataset <- gsub("patientDerived","patient-derived",se.rna$Dataset)
se.rna$Dataset <- gsub("patient-derived", "patient-\nderived", se.rna$Dataset)
se.rna$Dataset <- factor(se.rna$Dataset, c("patient-\nderived", "isogenic"))

rna.degs3 <- intersect(getDEGs.any(dea.rna, log2(1.3), 0.01), 
                       intersect(getDEGs.any(deas$RNA, FDR.thres=0.5),getDEGs.any(rna.dea.pD, FDR.thres=0.5)))
rna.degs2 <- intersect(getDEGs.any(dea.rna, log2(1.3), 0.01), 
                       intersect(getDEGs.any(deas$RNA, FDR.thres=0.25),getDEGs.any(rna.dea.pD, FDR.thres=0.25)))


p1 <- grid.grabExpr(draw(sechm(se.rna, rna.degs3, assayName="log2FC", top_annotation="genotype", gaps_at="Dataset", row_title="DEGs from\nmerged analysis", column_title_gp=gpar(fontsize=12.5), row_title_gp = gpar(fontsize = 12), use_raster=TRUE), merge_legends=TRUE))

set.seed(42)
go <- clusterGO(ea.rna$reg$goseq[ea.rna$reg$goseq$FDR < 0.01,], plot=FALSE)
go$Term <- breakStrings(go$term)
go2 <- go[!duplicated(go$cluster) & (-log10(go$FDR)>6 | go$enrichment>3.2),]
p2a <- ggplot(go, aes(log2(enrichment),-log10(FDR), colour=cluster)) +
  geom_point(aes(size=Significant), alpha=0.65) + geom_point(data=go2) +
  geom_label_repel(data=go2, aes(label=Term), size=3,
                   fill="#FFFFFFC8", min.segment.length=0) +
  scale_color_discrete(guide=FALSE)

terms <- unique(unlist(lapply(ea.rna[1:3], FUN=function(x){
  head(x$goseq$term[which(x$goseq$FDR<0.05)],5)})))
d <- lapply(ea.rna[1:3], FUN=function(x){
  x <- x$goseq
  x[which(x$term %in% terms), c("term","Significant","enrichment","PValue","FDR")]
})
d <- d[c(2,1,3)]
names(d) <- c("WBS\nvs CTL", "Copy-\nnumber", "7Dup\nvs CTL")
d <- dplyr::bind_rows(d, .id="Comparison")
d <- d[which(!is.na(d$term)),]
d$Term <- breakStrings(d$term, 10)

ggplot(d, aes(Comparison, Term, size=-log10(FDR), colour=log2(enrichment))) + geom_point()
```

## Symmetry

```{r, fig.width=3, fig.height=3}
deasig <- dea.rna[rna.degs2,]
deasig$weight <- 1/(deasig$lfcSE.WBS+deasig$lfcSE.DUP)^2
table(sign(deasig$logFC.WBS)==sign(deasig$logFC.DUP))/nrow(deasig)
mod <- MASS::rlm(deasig$logFC.DUP~0+deasig$logFC.WBS, weights=deasig$weight, wt.method="inv.var")
# deasym <- dea.rna[intersect(rna.degs2, getDEGs(dea.rna, log2(1.2), 0.01)),]
# mod2 <- MASS::rlm(deasym$logFC.DUP~0+deasym$logFC.WBS, weights=deasym$weight, wt.method="inv.var")

ggplot(deasig, aes(logFC.WBS, logFC.DUP)) + 
  geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + 
  ggpointdensity::geom_pointdensity(size=1) +
  geom_abline(slope=-1, linetype="dashed") + 
  geom_abline(slope=coef(mod), size=1.5, color="blue") + 
  scale_color_viridis_c(guide = "none") +
  coord_cartesian(ylim=c(-2.5,2.6), xlim=c(-2.5,2.5)) +
  annotate(geom="text", x=-1.9, y=-2, label="slope=-0.4")
```

### Asymmetry

```{r}
dea.rna$excl.WBS <- abs(dea.rna$logFC.WBS)>0.25 & dea.rna$FDR.WBS<0.01 & dea.rna$FDR.DUP>0.5 & abs(dea.rna$logFC.DUP)<pmin(abs(dea.rna$logFC.WBS)*0.25, 0.2)
excl.WBS <- row.names(dea.rna)[which(dea.rna$excl.WBS)]
dea.rna$excl.DUP <- abs(dea.rna$logFC.DUP)>0.25 & dea.rna$FDR.DUP<0.01 & dea.rna$FDR.WBS>0.5 & abs(dea.rna$logFC.WBS)<pmin(abs(dea.rna$logFC.DUP)*0.25, 0.2)
excl.DUP <- row.names(dea.rna)[which(dea.rna$excl.DUP)]
```





```{r}
asd <- readRDS("../extData/ID_ASD_genes.rds")
asd$SPARK <- readLines("../extData/spark.genes")
sfari <- intersect(as.character(unlist(asd$sfari[as.character(1:3)])), rownames(se.rna))
sfari <- sapply(sfari, FUN=function(x){
  for(i in as.character(1:3)){
    if(x %in% asd$sfari[[i]]) return(i)
  }
  return(NA)
})

asdg <- intersect(rna.degs3, c(names(sfari), asd$SPARK))

rowData(se.rna)$SFARI <- NA_character_
rowData(se.rna)[names(sfari),"SFARI"] <- sfari
rowData(se.rna)$AutismKB <- rowData(se.rna)$SPARK <- rowData(se.rna)$MSSNG <- rowData(se.rna)$eichler <- FALSE
rowData(se.rna)[intersect(row.names(se.rna), asd$MSSNG),"MSSNG"] <- TRUE
rowData(se.rna)[intersect(row.names(se.rna), asd$SPARK),"SPARK"] <- TRUE
rowData(se.rna)[intersect(row.names(se.rna), asd$EichlerList),"eichler"] <- TRUE
rowData(se.rna)[intersect(row.names(se.rna), asd$AutismKB),"AutismKB"] <- TRUE

asd2 <- asd[c(1:4,7:9)]
asd2$SFARI.S <- asd$sfari$S
asd2[["SFARI 1-2"]] <- c(asd$sfari[["1"]],asd$sfari[["2"]])
asd2[["SFARI 3-5"]] <- unlist(asd$sfari[c("3",4:5)])
names(asd2)[[5]] <- "ASD\nVelmeshev (2019)"
# ea <- plEA(row.names(dea.rna)[!is.na(dea.rna$PValue)], rna.degs, sets = asd2)
# ea$term <- row.names(ea)
# ea$proportion <- ea$overlap/ea$nbInSet
# p <- ggplot(ea, aes(enrichment, -log10(FDR))) + geom_point(aes(size=overlap, colour=proportion), alpha=0.7) + geom_text_repel(aes(label=term)) + scale_y_log10() + scale_color_gradient(low="lightblue", high="darkblue") + ggtitle("Overlap with ASD genes")
# p3 <- grid.grabExpr(draw(sechm(se.rna, asdg, assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_at="Dataset", anno_rows = c("SPARK","SFARI"), row_names_gp=gpar(fontsize=10), column_title_gp=gpar(fontsize=12.5), row_title="Top ASD DEGs", use_raster=TRUE), merge_legends=TRUE, heatmap_legend_side="left", annotation_legend_side="left"))
asdg <- setdiff(asdg, c("ACHE","TMLHE","PAX5"))
p3 <- grid.grabExpr(draw(sechm(se.rna, features=asdg, assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_at="Dataset", left_annotation = c("SPARK","SFARI"), row_names_gp=gpar(fontsize=8), column_title_gp=gpar(fontsize=12.5), row_title="Top ASD DEGs", use_raster=TRUE, show_annotation_legend=FALSE, show_heatmap_legend=FALSE, row_title_gp = gpar(fontsize = 12))))
```



```{r}
# ion-channel
mg2 <- c("ANXA6","ANO3","RYR2","SLC17A","TTYH2","KCNE5","REST","JPH2","ITPR1","HCN4","CACNA1G","CANCA1I","JPH3","KCNMA1","KCNK12","KCNC3","GRIN1","KCNK4","KCNA5","KCNA4","CACNA1E","NALCN","TRPM2","SHROOM2","KCNA2","ASIC1","FKBP1B","KCNS2","GABRA2","GABRA3","GABRG2","GRIN2B","KCNQ3","GRIK3","GRIK4")
p4a <- grid.grabExpr(draw(sechm(se.rna, mg2, assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_at="Dataset", row_title="ion channel DEGs", row_names_gp=gpar(fontsize=10), column_title_gp=gpar(fontsize=12.5)), merge_legends=TRUE))

gg <- intersect(rna.degs3,unique(unlist(gsets[grep("ION_CHANNEL", names(gsets))])))
p4b <- grid.grabExpr(draw(sechm(se.rna, gg, assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_at="Dataset", row_title="ion channel related DEGs", show_rownames=TRUE, breaks=0.985, column_title_gp=gpar(fontsize=12.5), row_names_gp=gpar(fontsize=10)), merge_legends=TRUE))


# gg2 <- list(channel=intersect(gsets[[grep("VOLTAGE_GATED_ION_CHANNEL_ACTIVITY",names(gsets))]], c(rna.degs3,"KCNK12","GRIN2B","KCNK4","KCNA4")),
#             regulator=intersect(gsets[[grep("ION_CHANNEL_REGULATOR_ACTIVITY",names(gsets))]], rna.degs3))
# convert to more recent GO terms:
ic <- union(gsets[[grep("GO_VOLTAGE_GATED_ANION_CHANNEL_ACTIVITY",names(gsets))]],
            gsets[[grep("GO_VOLTAGE_GATED_CATION_CHANNEL_ACTIVITY",names(gsets))]])
icr <- union(gsets[[grep("GO_REGULATION_OF_ANION_CHANNEL_ACTIVITY",names(gsets))]],
            gsets[[grep("GO_REGULATION_OF_CATION_CHANNEL_ACTIVITY",names(gsets))]])
gg2 <- list(channel=intersect(ic, c(rna.degs2,"KCNK12","GRIN2B","KCNK4","KCNA4")),
            regulator=intersect(icr, rna.degs2))
rowData(se.rna)$channel <- FALSE
rowData(se.rna)$channel[row.names(se.rna) %in% gg2$channel] <- TRUE
rowData(se.rna)$type <- factor(c("channel regulators","ion channels")[1+as.integer(rowData(se.rna)$channel)])
# p4c <- grid.grabExpr(draw(sechm(se.rna, unique(unlist(gg2)), assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_at="Dataset", row_title="ion channel related DEGs", show_rownames=TRUE, row_names_gp=gpar(fontsize=9.5), column_title_gp=gpar(fontsize=12.5), breaks=0.985, use_raster=TRUE, show_annotation_legend=FALSE, show_heatmap_legend=FALSE), merge_legends=TRUE))
g <- unique(unlist(gg2))
p4c <- grid.grabExpr(draw(sechm(se.rna, unique(unlist(gg2)), assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_row="type", gaps_at="Dataset", show_rownames=TRUE, row_names_gp=gpar(fontsize=8), column_title_gp=gpar(fontsize=12.5), breaks=0.985, use_raster=TRUE), merge_legends=TRUE, heatmap_legend_side="left", annotation_legend_side="left"))

gg3 <- gg2
names(gg3) <- c("ion channels","regulators")
gg3 <- lapply(gg3, FUN=function(x){
  intersect(x, intersect(
    getDEGs(deas$RNA, logFC.thres = log2(1.25), FDR.thres = 0.01),
    union(
      getDEGs(subset_mDEA(deas$RNA, "WBS"), logFC.thres = log2(1.15), FDR.thres = 0.05),
      getDEGs(subset_mDEA(deas$RNA, "DUP"), logFC.thres = log2(1.15), FDR.thres = 0.05)
    )))
})
gg3$channels <- setdiff(unique(c(gg3$channels, "KCNK12","GRIN2B","KCNK4","KCNA4","HCN4")),
                        c("CACNA1I"))
gg3$regulators <- unique(c(gg3$regulators, "ACTN2", "GNB5", "FKBP1B", "MAPK8IP2","ITGB1"))
levels(rowData(se.rna)$type)[1] <- "regulators"
p4d <- grid.grabExpr(draw(sechm(se.rna, unlist(gg3[2:1]), assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_row="type", gaps_at="Dataset", show_rownames=TRUE, row_names_gp=gpar(fontsize=8), column_title_gp=gpar(fontsize=12.5), breaks=0.985, use_raster=TRUE, row_title_gp = gpar(fontsize = 12), show_annotation_legend=FALSE, show_heatmap_legend=FALSE), merge_legends=TRUE))
```

```{r}
gt <- getWordsFromString(ea.rna$reg$goseq$genes[ea.rna$reg$goseq$term=="cytoplasmic translation"])
gt <- setdiff(intersect(gt, rna.degs), c("RPL38", "RPL39", "RPL41", "RPL36A","RPL24", "RPL26", "RPL17", "RPL31", "CPEB2"))
p5 <- grid.grabExpr(draw(sechm(se.rna, gt, assayName="log2FC", do.scale=FALSE, top_annotation=c("genotype"), gaps_at="Dataset", row_title="Cytoplasmic translation", show_rownames=TRUE, row_names_gp=gpar(fontsize=8), column_title_gp=gpar(fontsize=12.5), breaks=0.985, use_raster=TRUE, row_title_gp = gpar(fontsize = 12)),
  heatmap_legend_side="left", annotation_legend_side="left", merge_legends=TRUE))
```


```{r, fig.width=10, fig.height=3}
# c(0.42,0.3,0.3)
mp2 <- plot_grid(rel_widths=c(0.38,0.3,0.34), scale=0.95,
  p4d, p5, p3, nrow=1 #, labels=LETTERS[3:5]
)
mp2
```

# Protein-level

```{r}
se.prot <- toSymbol(readRDS("../clean/Neurons/Protein/Neurons.Protein.merged.SE.rds"))
se.prot <- se.prot[,se.prot$genotype!="AtWBS"]
se.prot$genotype <- droplevels(se.prot$genotype)
levels(se.prot$genotype)[2] <- "CTL"

dea.prot <- toSymbol(readRDS("../clean/Neurons/Protein/Neurons.Protein.merged.DEA.rds"))
se.prot$system <- gsub("patientDerived", "patient-derived", se.prot$Dataset)
se.prot <- se.prot[rowSums(is.na(assays(se.prot)$intensity))<3,]
se.rna$system <- gsub("\n","",se.rna$Dataset)

adegs <- unique(c(rna.degs3, getDEGs.any(dea.prot, FDR.thres=0.1)))

m <- lapply(list("Regression\non copynumber"=NULL, WBS="WBS", DUP="DUP"), FUN=function(x){
  rna <- subset_mDEA(dea.rna, x)
  prot <- subset_mDEA(dea.prot, x)
  degs <- union(getDEGs(rna, log2(1.3), 0.01), getDEGs(prot))
  degs <- intersect(degs, intersect(row.names(prot),row.names(rna)))
  degs <- intersect(degs, rna.degs3)
  merge(rna[degs,], prot[degs,], by="row.names", suffix=c(".RNA", ".Protein"))
})
m2 <- dplyr::bind_rows(m, .id="Comparison")
m2$Comparison <- factor(m2$Comparison, c("Regression\non copynumber", "WBS", "DUP"),
                        c("Regression\non copynumber", "WBS vs CTL", "DUP vs CTL"))
cap <- function(x, what, at=3){
  x$capped <- FALSE
  w <- which(abs(x[[what]])>at)
  x[[what]][w] <- sign(x[[what]][w])*at
  x$capped[w] <- TRUE
  x
}
slopes <- dplyr::bind_rows(lapply(split(m2,m2$Comparison), FUN=function(x){
  data.frame(slope=as.numeric(coef(MASS::rlm(x$logFC.Protein~0+x$logFC.RNA))),
             intercept=0)
}), .id="Comparison")
m2 <- cap(m2, "logFC.RNA")
m2 <- cap(m2, "logFC.Protein")
p6 <- ggplot(m2, aes(logFC.RNA, logFC.Protein)) + 
  geom_abline(slope=1, intercept=0, linetype="dashed") +
  geom_hline(yintercept=0, linetype="dashed", colour="grey") + 
  geom_vline(xintercept=0, linetype="dashed", colour="grey") + 
  geom_point(aes(shape=capped)) + 
  facet_wrap(~Comparison, scales = "free") + theme(legend.position="none") +
  geom_abline(data=slopes, aes(slope=slope, intercept=intercept), size=1.2, color="blue")

```


```{r}
go <- c("CTRL"=2,"WBS"=1,"AtWBS"=1.5,"DUP"=3)
ll <- list(
  RNA=se.rna[,order(go[as.character(se.rna$genotype)])],
  Protein=se.prot[,order(go[as.character(se.prot$genotype)])])
se <- SEtools::mergeSEs(ll, "log2FC", do.scale=FALSE)
se$Dataset <- factor(se$Dataset, levels=c("RNA","Protein"))
se$system <- gsub("patient-derived","patient-\nderived",se$system)
se$genotype <- relevel(se$genotype, "WBS")
se <- se[,order(se$genotype)]

p7b <- grid.grabExpr(draw(sechm(se, gt, assayName="log2FC", gaps_at="Dataset", top_annotation=c("genotype","system"), row_title="Cytoplasmic\ntranslation", use_raster=TRUE, 
                                show_rownames=FALSE, row_title_gp = gpar(fontsize = 12)), merge=FALSE))
```


```{r, fig.width=9, fig.height=7}
pp <- plot_grid(
  plot_grid(p1, p2a, rel_widths=c(2,3), scale=0.95, labels="AUTO"),
  plot_grid(rel_widths=c(0.38,0.3,0.34), scale=0.95, p5, p4d, p3, nrow=1,
            labels=LETTERS[3:5]),
  plot_grid(p6, p7b, rel_widths=c(3,2.2), scale=0.95, labels=LETTERS[6:7]),
  nrow=3, rel_heights=c(1.5,2.1,1.4)
)
ggsave("neurons_omics_overview5.pdf", pp, width=9, height=7)
pp
```










